spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.94.21.220:3306/blog?useUnicode=true&amp;characterEncoding=UTF-8&amp;useSSL=false
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none
#    show-sql: true

logging:
  level:
    root: warn
    com.lrm: info
  file: log/blog-pro.log

server:
  port: 80
  address: 0.0.0.0
